### ISSUE TITLE
522错误

### ISSUE THREAD

**Issue by goodwin-lvzhou** [ILLKX/Windows#2]
连接好像出错了，报522代码，是否可以帮忙看看是什么情况吗？感谢
浏览器：chrome
系统：windows
报错连接：https://download.testip.xyz/Windows/zh-hans_windows_xp_professional_with_service_pack_3_x86_cd_vl_x14-74070.iso
错误页面：
![image](https://github.com/ILLKX/Windows/assets/149861600/6b9b53a3-3790-4f3c-b3ea-7d24f0706b2b)

**Comment by ILLKX** [comment]
Sorry about that. Fixed now.
